Always close mapper plugins (#22722)
Since we changed how we track properly shut down plugins to depend on
`SignalCancellation` (https://github.com/pulumi/pulumi/pull/22569), we
started erroring on every plugin that doesn't have a bulk shutdown via
`defaultHost`. This includes the mapper used in converts, which
currently always errors:

    $ pulumi convert --from terraform --language pcl --out ./out
    Converting from terraform...
error: Detected that
/Users/ianwahbe/.pulumi/plugins/resource-aws-v7.24.0/pulumi-resource-aws
exited prematurely.
This is *always* a bug in the provider. Please report the issue to the
provider author as appropriate.
To assist with debugging we have dumped the STDOUT and STDERR streams of
the plugin:

    Converting to pcl...
warning: main.pp:0,8-13: package block label is deprecated; Package
block labels should be replaced by baseProviderName.

This PR extends `(plugin.hostManagedProvider).Close` to exhibit the same
shutdown behavior as `(plugin.defaultHost).Close`. This effectively
deepens the fix applied by https://github.com/pulumi/pulumi/pull/22692,
so I've reverted that PR in this one.